---
name: "VARatio"
guid: "c8a3f1e2-5b7d-4a9c-8e6f-3d2a1b0c9e8d"
version: "1.0.0.0"
targetAbi: "10.11.0.0"
framework: "net9.0"
overview: "Detect variable aspect ratios in movies and generate .var timing files"
description: >
  VARatio analyzes video files for variable aspect ratios (e.g. IMAX scenes
  in Interstellar, The Dark Knight) and writes a custom .var file alongside
  the movie to encode the timing and ratio of each detected change.
  Black frames and fade transitions are handled gracefully.
category: "General"
owner: "toad"
artifacts:
  - "Jellyfin.Plugin.VARatio.dll"
  - "Jellyfin.Plugin.VARatio.pdb"
changelog: changelog
